# Sample properties used by Spring configuration in ApplicationConfig.


server:
  port: 8182
spring:
  thymeleaf:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?allowPublicKeyRetrieval=true&useSSL=false
    username: admin1
    password: admin1
    #url: jdbc:mysql://bnybtsjyvua3n9wzef56-mysql.services.clever-cloud.com:20399/bnybtsjyvua3n9wzef56
    #username: unu4ppqefgjupna6
    #password: XWdgTErfq5eQuOqT0yc
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  database-platform: org.hibernate.dialect.MySQL5Dialect
  config:
    activate:
      on-profile: dev
application:
  domain: localhost

